[package]
name = "NaiveBayes"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
log = "0.4.25"
serde = { version = "1.0.217", features = ["derive"] }
actix-web = "4"
bincode = "1.3.3"
chrono = "0.4.39"
regex = "1.11.1"